 http://localhost:3003/api/blogs/
###

GET   http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2NTk1MmY5YTA1Y2MwN2U4MjZkOWQxNWIiLCJpYXQiOjE3MDQyNzYwNjB9.a_ZKsRM9gaN4sAiQ_ElgKQQyQtWPJ_a3O6J_jXNl0RU
###
DELETE   http://localhost:3003/api/blogs/6595776989ea0f75ffeaef42
###
PUT http://localhost:3003/api/blogs/65952fc305cc07e826d9d162
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2NTk1MmZkNjA1Y2MwN2U4MjZkOWQxNjUiLCJpYXQiOjE3MDQyNzU5MzN9.yeAPtP5c88AQBUIFlGp9OmfLsXZOmAzY5JNJVggBAHU


{
  "likes": 9999
} 
###

POST  http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title":"pepe test 2",
  "author": "pepe",
  "url":"www.digimon.jp"
}

###

POST  http://localhost:3003/api/users/
Content-Type: application/json

{
  "username":"user2",
  "name": "batman",
  "password":"123456"
}
###

http://localhost:3003/api/users/

###


POST  http://localhost:3003/api/login/
Content-Type: application/json

{
  "username":"user1",
  "password":"123456"
}

###

POST  http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2NTk1MmZkNjA1Y2MwN2U4MjZkOWQxNjUiLCJpYXQiOjE3MDQyNzU5MzN9.yeAPtP5c88AQBUIFlGp9OmfLsXZOmAzY5JNJVggBAHU

{
 "title":"Blog 4",
  "author": "batman",
  "url":"www.satifayer.com"
}

###
DELETE http://localhost:3003/api/blogs/6595784489ea0f75ffeaef5c
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2NTk1MmZkNjA1Y2MwN2U4MjZkOWQxNjUiLCJpYXQiOjE3MDQyNzU5MzN9.yeAPtP5c88AQBUIFlGp9OmfLsXZOmAzY5JNJVggBAHU
